[project]
name = "sumarization-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
